GET http://localhost:8081/users

### Obtener usuario por ID

GET http://localhost:8081/users/4

### Crear usuario
POST http://localhost:8081/users
Content-Type: application/json

{
  "nombre": "Jose",
  "email": "jose@gmail.com",
  "password": "123456"
}

### Modificar usuario
PATCH http://localhost:8081/users/12
Content-Type: application/json

{
  "nombre": "Jose"
}

### Eliminar usuario por ID
DELETE http://localhost:8081/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibm9tYnJlIjoiUm95IExlZSIsImNvcnJlbyI6Imx1bmFybW9yZXJAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ2NzE2OTg0LCJleHAiOjE3NDY3MjQxODR9.qi1Uh-4Rzn5w65X-U_n1sndKXRTqOG8JE5kORAezHwA

### Login 
POST http://localhost:8081/login
Content-Type: application/json

{
  "correo": "lunarmorer@gmail.com",
  "password": "123321"
}

### Register 
POST http://localhost:8081/register
Content-Type: application/json

{
  "nombre": "Roy Lee",
  "apellido": "Lunar",
  "sapellido": "Moré",
  "correo": "lunarmorer@gmail.com",
  "password": "123321",
  "respassword": "123321"
}

### Obtener info del ultimo
GET http://localhost:8081/users/5/info/last
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibm9tYnJlIjoiUm95IExlZSIsImNvcnJlbyI6Imx1bmFybW9yZXJAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ2NzE2OTg0LCJleHAiOjE3NDY3MjQxODR9.qi1Uh-4Rzn5w65X-U_n1sndKXRTqOG8JE5kORAezHwA

### Obtener planes de un usuarios
GET http://localhost:8081/trains/user/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibm9tYnJlIjoiUm95IExlZSIsImNvcnJlbyI6Imx1bmFybW9yZXJAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ2NzE2OTg0LCJleHAiOjE3NDY3MjQxODR9.qi1Uh-4Rzn5w65X-U_n1sndKXRTqOG8JE5kORAezHwA

### Obtener paginas usuarios
GET http://localhost:8081/users/paginate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibm9tYnJlIjoiUm95IExlZSIsImNvcnJlbyI6Imx1bmFybW9yZXJAZ21haWwuY29tIiwicHJvZmlsZV9pbWciOiJwZnAtMTc0NzQzNzI4Nzc5OS03Nzk4MzcyNTcuanBnIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ3NTk1OTI5LCJleHAiOjE3NDc2MDMxMjl9.EUylJPYylvfHOpiwb-KhYvsR7lmULODAQCmDwCvD5H8

### CREAR ENTRENAMIENTOS
POST http://localhost:8081/trains/autocreate
Content-Type: application/json

{
  "userId": 4,
  "objetivo": "fuerza",
  "nivel": "basico"
}

### ASd
GET http://localhost:8081/trains/plan/6