GET http://localhost:8081/users

### Obtener usuario por ID

GET http://localhost:8081/users/4

### Crear usuario
POST http://localhost:8081/users
Content-Type: application/json

{
  "nombre": "Jose",
  "email": "jose@gmail.com",
  "password": "123456"
}

### Modificar usuario
PATCH http://localhost:8081/users/12
Content-Type: application/json

{
  "nombre": "Jose"
}

### Eliminar usuario por ID
DELETE http://localhost:8081/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwibm9tYnJlIjoiU2FtdWVsIiwiY29ycmVvIjoic2FtdWVsbHVuYXJAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDYyNzg4OTUsImV4cCI6MTc0NjI4NjA5NX0.ye0EXxFiyeBvsF3I0--vDyGx0Jf72H7iLsjqqxItIgk

### Login 
POST http://localhost:8081/login
Content-Type: application/json

{
  "correo": "lunarmorer@gmail.com",
  "password": "123321"
}